# Generated by Django 4.1.3 on 2022-11-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("description", models.TextField(max_length=10000)),
                ("rating", models.DecimalField(decimal_places=1, max_digits=3)),
                ("ratings_num", models.IntegerField()),
                ("avg_time", models.IntegerField()),
                ("type", models.CharField(max_length=300)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
    ]
