# Generated by Django 4.1.3 on 2022-11-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Eateries", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurants",
            name="image",
        ),
        migrations.AddField(
            model_name="restaurants",
            name="image_url",
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
