# Generated by Django 4.1.3 on 2022-11-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Eateries", "0002_remove_restaurants_image_restaurants_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurants",
            name="image_url",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
