# Generated by Django 4.1.3 on 2022-11-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Eateries", "0004_food"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurants",
            name="menu",
            field=models.ManyToManyField(to="Eateries.food"),
        ),
    ]
