# Generated by Django 4.1.3 on 2022-11-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Eateries", "0006_alter_restaurants_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurants",
            name="loaction",
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
