# Generated by Django 4.1.3 on 2022-11-04 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Eateries", "0007_restaurants_loaction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="restaurants",
            old_name="loaction",
            new_name="location",
        ),
    ]
